
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Iron King',18,'Julie Kagawa','conference',2012,'http://d.gr-assets.com/books/1327877670l/6644117.jpg', 'false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Iron Queen',20,'Julie Kagawa','conference',2013,'http://vignette3.wikia.nocookie.net/ironfey/images/a/a9/The_Iron_Queen.jpg/revision/latest?cb=20110415084109','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Iron Daughter',17,'Julie Kagawa','conference',2012,'http://vignette4.wikia.nocookie.net/ironfey/images/0/03/9780373210138_TS_PRD.jpg/revision/latest?cb=20110415083826','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Iron Traitor',19,'Julie Kagawa','conference',2015,'http://t0.gstatic.com/images?q=tbn:ANd9GcT_U_uVkzGy1nONGUcQW40Xi-TEuRYf6LmAYnCIbptVDKgG_vXD','false');

INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Little Red Riding Hood',22,'Charles Perault','editorship',1697,'http://news.nationalgeographic.com/content/dam/news/photos/000/738/73840.ngsversion.1422284208449.adapt.768.1.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Winnie The Pooh',33,'Ernest H. Shepard','editorship',1983,'http://static.tvtropes.org/pmwiki/pub/images/winnie-the-pooh-book_1724.png','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('The Jungle Book',48,'Rudyard Kipling','editorship',2005,'http://t2.gstatic.com/images?q=tbn:ANd9GcR50w94R954Wff4Ei4fa-mmedWXDDutQ36YnAOkkI-uzqyi30dP','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Mickey Mouse',50,'Walt Disney','editorship',1990,'https://upload.wikimedia.org/wikipedia/en/d/d4/Mickey_Mouse.png','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('The Sleeping Beauty',29,'Ivan Vsevolozhsky','editorship',1890,'http://ecx.images-amazon.com/images/I/51ZDbu4KJ-L.jpg','false');

INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Little Match Girl',65,'Hans Christian Andersen','conference',1845,'http://t3.gstatic.com/images?q=tbn:ANd9GcRwrSNHbGa1clZEVDG7EfTCSXhwNSbn256lvP4-r61nRFFwkA8i','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Karma',46,'Gabriela Febriana','conference',1860,'http://d.gr-assets.com/books/1334949203l/8828714.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Doraemon',190,'Fujiko F Fujio','conference',1983,'http://www.watchcartoononline.com/thumbs/Doraemon-Episode-26-English-Dubbed.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('A Study in Scarlet',57,'Arthur Conan Doyle','conference',1887,'http://t0.gstatic.com/images?q=tbn:ANd9GcQEssmBectmN852GAuvitvE5j2QLBbTv2SeXYjADwNGFRrqj-wc','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Hounds of Baskerville',38,'Arthur Conan Doyle','conference',1902,'http://t2.gstatic.com/images?q=tbn:ANd9GcTmx8e04bFkg4Z2tjoFfLAu0IEtKlm0HVVYJgRIwO8CRgkZxZkx','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('The Sign of the Four',32,'Arthur Conan Doyle','conference',1890,'http://t1.gstatic.com/images?q=tbn:ANd9GcTGqsPacTrYsvl3uiNUbclatSZJTqsesCx50PtMvDgODgmkG4j7','false');

INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('The Little Mermaid',43,'Hans Christian Andersen','editorship',1983,'http://t2.gstatic.com/images?q=tbn:ANd9GcSEWTis5c7QHFsHRIp8Z3YnwsZuWtQltLZUmHVRVqxAY7Ag9dMa','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('The Snow Queen',55,'Hans Christian Andersen','editorship',1844,'http://t3.gstatic.com/images?q=tbn:ANd9GcRa5fBgCOoaXGWLzkQGTLSGztveyLU-ijTEknA821C17hZAesaY','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('The Ugly Duckling',42,'Hans Christian Andersen','editorship',1843, 'http://t2.gstatic.com/images?q=tbn:ANd9GcRFIxBcrN1CtnizcN9Sf3vpXYUULn5abwqLj7_SqeaYkxaBFxOI','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('The Emperors New Clothes',30,'Hans Christian Andersen','editorship',1837,'http://t1.gstatic.com/images?q=tbn:ANd9GcQ1URJWpDa8CaxtWKornPOdXtkWDijgC-DUCmDIg2VKqNPOGypM','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Thumbelina',50,'Hans Christian Andersen','editorship',1835,'http://t0.gstatic.com/images?q=tbn:ANd9GcR_JFzKkyoOQAnd7hP3Nu7O3KOSxCScnh7Iags5kcsivUnHkI1h','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Oliver Twist',50,'Charles Dickens','editorship',1837,'http://t2.gstatic.com/images?q=tbn:ANd9GcTNVgWO1Sl2y6kpXK2-Mv5QTvs5IAfW2MeEjJKwCwm-_SwqEKEc','false');

INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Bound Journal Medium',40,'Khadi Paper','journal',1983,'http://www.peterpauper.com/dealer/images/Leather-Jrn-Category.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Homage to Catalonia',13,'George Orwell','journal',1938,'http://t1.gstatic.com/images?q=tbn:ANd9GcRLKWf9voRG0Vl-tQpPBers8ZVgNe3A4qWA4uPChDBjzpsx10r2','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Burmese Days',82,'George Orwell','journal',1983,'http://t0.gstatic.com/images?q=tbn:ANd9GcQHdkmcFtC-RJup59sYcr8-A-_ZF4YTUp8aMDpSxoQ8kdiIH7hm','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Down and Out in Paris and London',50,'George Orwell','journal',1933,'http://t1.gstatic.com/images?q=tbn:ANd9GcTBmsUtStwW-kIF9mKaK4WjVZyb2LKeeHya1xP7uOBzdH5-QChC','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Autobiography of Mark Twain',88,'Mark Twain','journal',1835,'http://t3.gstatic.com/images?q=tbn:ANd9GcSuYwrxuQyf11T18tpeNuvkTyzETSzMACHoJaA-hdQUGzpvXt5c','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('The Prince and The Pauper',62,'Mark Twain','journal',1881,'http://t3.gstatic.com/images?q=tbn:ANd9GcQzJX8kPFz_nJONoGiqrGL1wR0yvJQ0VaysmJQ7R8JIrGXKvdKq','false');

INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Sword Art Online',12,'Kawahara Reki','conference',2010,'http://t3.gstatic.com/images?q=tbn:ANd9GcQL2s8z5aHb8E1U3xwxJ5cOw-9RmtlazW2IeIilJ6mhjg5gTpUn','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Beelzebub',24,'Ryuhei Tawamura','conference',2008,'https://upload.wikimedia.org/wikipedia/en/e/ea/Beelzebub_manga_Volume_1.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Rave Master',23,'Hiro Mashima','conference',1999,'https://upload.wikimedia.org/wikipedia/en/4/47/Rave_Volume_1.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Fairy Tail',22,'Hiro Mashima','conference',2006,'https://upload.wikimedia.org/wikipedia/en/e/e1/FairyTail-Volume_1_Cover.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Kuroko no Basuke',19,'Tadatoshi Fujimaki','conference',2008,'https://upload.wikimedia.org/wikipedia/en/7/79/Kuroko_no_Basuke_Cover.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Captain Tsubasa',13,'Matt Groening','conference',1981,'https://upload.wikimedia.org/wikipedia/en/6/67/CaptainTsubasa_vol01_Cover.jpg','false');

INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Crayon Shin-chan',28,'Yoshito Usui','conference',1990,'https://upload.wikimedia.org/wikipedia/en/9/92/Crayon_Shin-chan_vol_1_cover.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Great Teacher Onizuka',18,'Tooru Fujisawa','conference',1998,'https://upload.wikimedia.org/wikipedia/en/a/a8/GTO_manga.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Chibi Maruko-chan',8,'Momoko Sakura','conference',1986,'https://upload.wikimedia.org/wikipedia/en/3/39/Chibi_maruko-chan_comic_no_1_cover.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('xxxHolic',50,'Clamp','conference',2003,'https://upload.wikimedia.org/wikipedia/en/e/ee/XxxHolic_vol1_Cover.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Code Geass',38,'Ichiro Okouichi','conference',2006,'https://upload.wikimedia.org/wikipedia/en/0/08/Code_Geass_DVD_Part3.png','false');

INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('The Old Mand and The Sea',72,'Ernest Hemingway','journal',1952,'http://t2.gstatic.com/images?q=tbn:ANd9GcRHbvjZSHpj14VM8ayLYWh7PEQj37lUzVAtiA1Ml8kQ4ewj13bJ','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('A Farewell to Arms',26,'Ernest Hemingway','journal',1929,'http://t3.gstatic.com/images?q=tbn:ANd9GcSgPU1MZ79RUHyOyWFFGLf-Q5fmdpITU3YX-H4z0MsMNqyvFtNv','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('The Sun also Rises',83,'Ernest Hemingway','journal',1926,'http://t3.gstatic.com/images?q=tbn:ANd9GcSZZZeQqiSptBUzuD5nZGnNmx1qNozV5tNCuchUSuzD0hF2fDJb','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('The Call of The Wild',31,'Jack London','journal',1876,'http://t3.gstatic.com/images?q=tbn:ANd9GcSbK7ogkTV8jtAp6N-MkSnyNWzahcLpNZBt-buWTxIXbKNjmYIp','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Annabel Lee',20,'Edgar Allan Poe','journal',1849,'http://t1.gstatic.com/images?q=tbn:ANd9GcTwDK5Q_IiDPUTLoOhUI8X5Q4ynFOqpy5o4vdK_UPXyedAogaje','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Eureka',50,'Edgar Allan Poe','journal',1848,'http://t1.gstatic.com/images?q=tbn:ANd9GcSNoypZbd1J9pjaG4-ubvebrlzuR_V4WU5n5oYjYADjrAON8EuT','false');

INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Iron Knight',18,'Julie Kagawa','conference',2014,'http://ecx.images-amazon.com/images/I/51R8oESRUYL._SX324_BO1,204,203,200_.jpg','false');
INSERT INTO publications (title, price, author, pub_type, pub_year, picture, pause) VALUES ('Chobits',48,'Clamp','conference',2000,'https://upload.wikimedia.org/wikipedia/en/c/cd/Chobites_volume_1_cover.jpg','false');

insert into publications (title, price, author, pub_type, pub_year, isbn, picture, pause) values ('Introduction to Algorithms',20,'Thomas H. Cormen','book/collection',2000,'978-0262033848','https://upload.wikimedia.org/wikipedia/en/4/41/Clrs3.jpeg','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, pause) values ('My Book',100,'Gabriela Febriana','book/collection',2017,'666','false');
insert into publications (title, price, author, pub_type, picture, pause) values ('Doraemon vol. 1',5,'Fujiko F. Fujio','book/collection', 'https://upload.wikimedia.org/wikipedia/en/c/c8/Doraemon_volume_1_cover.jpg','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, pause) values ('My Editorship',50,'Natalia Z.','editorship',2017,'666','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, pause) values ('My Conference',15,'John Z.','conference',2017,'666','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, pause) values ('My Journal',20,'Emily B.','journal',2000,'2020202331','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, picture, pause) values ('The Large Scale Structure of Space-time',35,'S.W. Hawking','book/collection',1973,'2217813-2353','http://assets.cambridge.org/97805210/99066/cover/9780521099066.jpg','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, picture, pause) values ('The Maze Runner',150,'James Dashner','book/collection',2010,'1123413-55375-3','http://img4.wikia.nocookie.net/__cb20120701084826/mazerunner/images/8/8b/Mazerunner.jpg','false');
insert into publications (title, price, author, pub_type, pub_year, picture, pause) values ('To Kill a Mockingbird',52,'Harper Lee','editorship',1960,'https://upload.wikimedia.org/wikipedia/en/7/79/To_Kill_a_Mockingbird.JPG','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, picture, pause) values ('Into the Woods',40,'Stephen Sondheim','book/collection',1989,'15556755375-3','https://upload.wikimedia.org/wikipedia/en/6/6a/Into_the_Woods_poster.jpg','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, picture, pause) values ('The Fault in Our Stars',55,'John Green','book/collection',2012,'212745147485','https://upload.wikimedia.org/wikipedia/en/a/a9/The_Fault_in_Our_Stars.jpg','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, picture, pause) values ('Divergent',80,'Veronica Roth','book/collection',2011,'2885693816','https://upload.wikimedia.org/wikipedia/en/f/f4/Divergent_(book)_by_Veronica_Roth_US_Hardcover_2011.jpg','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, picture, pause) values ('Gone Girl',43,'Gillian Flynn','book/collection',2012,'2928147013','http://gillian-flynn.com/gone-girl/gone-girl-book-cover-med.jpg','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, picture, pause) values ('The Great Gatsby',66,'F.Scott Fitzgerald','book/collection',1925,'29374755','https://s3.amazonaws.com/rapgenius/photo_15670_0-53.png','false');
insert into publications (title, price, author, pub_type, pub_year, isbn, picture, pause) values ('The Giver',40,'Lois Lowry','book/collection',1993,'293947518','http://ecx.images-amazon.com/images/I/81cJChEQjSL.jpg','false');
insert into publications (title, price, author, pub_type, pub_year, pause) values ('Research in Algorithms',20,'Mark J.','journal',2000,'false');
insert into publications (title, price, author, pub_type, pub_year, pause) values ('Fair Resource Allocation',15,'Gabriela Febriana','journal',2015,'false');
insert into publications (title, price, author, pub_type, pub_year, pause) values ('Page Rank Algorithm',55,'Jack A.','journal',2000,'false');
insert into publications (title, price, author, pub_type, pub_year, pause) values ('Recommender Systems',20,'Jack C.','journal',2000,'false');
insert into publications (title, price, author, pub_type, pub_year, pause) values ('Research in Dijkstra Algorithm',10,'David B.','journal',2000,'false');
insert into publications (title, price, author, pub_type, pub_year, pause) values ('A-Star Algorithm',15,'Brian D.','journal',1999,'false');
insert into publications (title, price, author, pub_type, pub_year, pause) values ('Data-Mining and Warehousing',16,'Andy D.','journal',1998,'false');